{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thorax-kubernetes-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thorax-kubernetes-controller.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
