[package]
name = "thorax-run"
version.workspace = true
edition.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
clap.workspace = true
thorax-frontend.workspace = true
thorax-ops.workspace = true
